import Settings from "@/components/Areas/Settings/SettingManagement";
import { Metadata } from "next";




export const metadata: Metadata = {
  title: "Setting | Profer",
  description: "Generated by create next app",
};

export default function Setting(){



    return(<>
        <Settings></Settings>
    

    </>);
}