
import { CompanyManagement } from "@/components/Areas/CompaniesManagement/Managecompanies";
import { Metadata } from "next";




export const metadata: Metadata = {
  title: "Companies | Profer",
  description: "Generated by create next app",
};


export default function Companies(){


    return(<>
    
        <CompanyManagement></CompanyManagement>
    
    </>);
}