import { SignIn } from "@/components/Frontend/Signin/Signinfrontend";
import { Metadata } from "next";




export const metadata: Metadata = {
  title: "Search For Pros | Profer",
  description: "Generated by create next app",
};




export default function SigninFrontend(){

    return(<>

        <SignIn></SignIn>
    </>);
}