
import { Projectmanagement } from "@/components/Areas/ProjectsManagement/Projectmanagement";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Projects | Profer",
  description: "Generated by create next app",
};

export default function Projects(){



    return(<>
        <Projectmanagement></Projectmanagement>
    
    </>);
}