
import { UserManagement } from "@/components/Areas/UserManagement/Usermanagement";
import { Metadata } from "next";




export const metadata: Metadata = {
  title: "User Management | Profer",
  description: "Generated by create next app",
};

export default function Users(){


    return(<>
      <UserManagement></UserManagement>
    
    </>);
}