
import BiddingActivity from "@/components/Areas/BiddingManagement/BiddingManagement";
import { Metadata } from "next";



export const metadata: Metadata = {
  title: "Bidding | Profer",
  description: "Generated by create next app",
};

export default function Projects(){



    return(<>
      <BiddingActivity></BiddingActivity>
    
    </>);
}